import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";


export const metadata = {
  title: "NextGen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="pt-1" >
        <Nav/>
        <main>
        {children}
        </main>
        </body>  
    </html>
    
  );
}
