import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Foot from "./components/Foot";


export const metadata = {
  title: "NextGen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  >
        <div className="pt-1" >
        <Nav/>
        </div>
       
        <main>
        {children}
        </main>
        <Foot/>
        </body>  
       
    </html>
    
  );
}
